const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');
const React = require('react');
const ReactDOMServer = require('react-dom/server');

// Try to load config.json
let outputDirConfig = null;
try {
    const configPath = path.join(__dirname, '../config.json');
    if (fs.existsSync(configPath)) {
        const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
        if (config.outputPath) {
            outputDirConfig = path.isAbsolute(config.outputPath) 
                ? config.outputPath 
                : path.join(__dirname, '..', config.outputPath);
        }
    }
} catch (e) {
    console.warn('Failed to load config.json in process_single_file:', e.message);
}

// Next.js build output directory
const NEXT_BUILD_DIR = path.join(__dirname, '../.next');
const OUTPUT_DIR = outputDirConfig || path.join(__dirname, '../../output');
const POSTS_DIR = path.join(__dirname, '../posts');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// 1. Load CSS from Next.js build
// We need to find the main CSS file generated by Next.js
function getBuildCss() {
    const staticCssDir = path.join(NEXT_BUILD_DIR, 'static/css');
    if (!fs.existsSync(staticCssDir)) return '';
    
    let cssContent = '';
    const files = fs.readdirSync(staticCssDir);
    files.forEach(file => {
        if (file.endsWith('.css')) {
            cssContent += fs.readFileSync(path.join(staticCssDir, file), 'utf8');
        }
    });
    return cssContent;
}

const GLOBAL_CSS = getBuildCss();

// 2. Load HtmlBundler and components (We need to transpile or use ts-node)
// Since we are in a JS script, we can't directly import TSX components without babel/ts-node.
// A simpler approach is to use the existing `generate_portable_output.js` logic but enhanced:
// Instead of relying on Next.js 'export', we manually construct the HTML using the SAME template as the editor.

// However, we can't easily run React components in this raw Node script without a build step for this script itself.
// ALTERNATIVE: We can use the Next.js 'export' output (HTML files) and INLINE the resources.
// The user said the 'editor export' is perfect. The editor export uses `HtmlBundler`.
// `HtmlBundler` uses `renderToStaticMarkup` and `CssExtractor`.

// The key difference is `CssExtractor` runs in the browser and gets ALL styles.
// In Node, we don't have a browser.
// But we DO have the generated CSS files from the build.

// STRATEGY:
// 1. Read the Next.js exported HTML file (which has correct content structure but external links).
// 2. Extract the content part (inside <body>).
// 3. Inject it into our `HTML_TEMPLATE` (from `src/lib/export/template.ts`).
// 4. Inject the `GLOBAL_CSS` we read from `.next/static/css`.
// 5. Inject the Theme Script.

// Let's read the template first. We'll duplicate it here to avoid TS compilation issues.
const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en" data-theme="{{THEME}}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{TITLE}}</title>
    <style>
        /* Base Reset & Variables */
        :root {
            --background: 0 0% 100%;
            --foreground: 222.2 84% 4.9%;
            --card: 0 0% 100%;
            --card-foreground: 222.2 84% 4.9%;
            --popover: 0 0% 100%;
            --popover-foreground: 222.2 84% 4.9%;
            --primary: 222.2 47.4% 11.2%;
            --primary-foreground: 210 40% 98%;
            --secondary: 210 40% 96.1%;
            --secondary-foreground: 222.2 47.4% 11.2%;
            --muted: 210 40% 96.1%;
            --muted-foreground: 215.4 16.3% 46.9%;
            --accent: 210 40% 96.1%;
            --accent-foreground: 222.2 47.4% 11.2%;
            --destructive: 0 84.2% 60.2%;
            --destructive-foreground: 210 40% 98%;
            --border: 214.3 31.8% 91.4%;
            --input: 214.3 31.8% 91.4%;
            --ring: 222.2 84% 4.9%;
            --radius: 0.5rem;
            --chart-1: 12 76% 61%;
            --chart-2: 173 58% 39%;
            --chart-3: 197 37% 24%;
            --chart-4: 43 74% 66%;
            --chart-5: 27 87% 67%;
        }

        .dark {
            --background: 222.2 84% 4.9%;
            --foreground: 210 40% 98%;
            --card: 222.2 84% 4.9%;
            --card-foreground: 210 40% 98%;
            --popover: 222.2 84% 4.9%;
            --popover-foreground: 210 40% 98%;
            --primary: 210 40% 98%;
            --primary-foreground: 222.2 47.4% 11.2%;
            --secondary: 217.2 32.6% 17.5%;
            --secondary-foreground: 210 40% 98%;
            --muted: 217.2 32.6% 17.5%;
            --muted-foreground: 215 20.2% 65.1%;
            --accent: 217.2 32.6% 17.5%;
            --accent-foreground: 210 40% 98%;
            --destructive: 0 62.8% 30.6%;
            --destructive-foreground: 210 40% 98%;
            --border: 217.2 32.6% 17.5%;
            --input: 217.2 32.6% 17.5%;
            --ring: 212.7 26.8% 83.9%;
            --chart-1: 220 70% 50%;
            --chart-2: 160 60% 45%;
            --chart-3: 30 80% 55%;
            --chart-4: 280 65% 60%;
            --chart-5: 340 75% 55%;
        }
    </style>
    <style>
        {{CSS}}
    </style>
    <script>
        {{THEME_SCRIPT}}
    </script>
</head>
<body class="min-h-screen bg-bg-page font-sans antialiased">
    {{CONTENT}}
    <script>
        {{SCRIPT}}
    </script>
</body>
</html>`;

// Helper: Rename URL-encoded files and directories to Chinese
// We reuse this logic from generate_portable_output.js
function renameEncodedItems(dir) {
    const items = fs.readdirSync(dir);
    
    items.forEach(item => {
        const fullPath = path.join(dir, item);
        const stat = fs.statSync(fullPath);
        
        if (item.includes('%')) {
            try {
                const decodedName = decodeURIComponent(item);
                if (decodedName !== item) {
                    const newPath = path.join(dir, decodedName);
                    if (fs.existsSync(newPath)) {
                        fs.rmSync(newPath, { recursive: true, force: true });
                    }
                    fs.renameSync(fullPath, newPath);
                    if (stat.isDirectory()) {
                         renameEncodedItems(newPath);
                    }
                    return; 
                }
            } catch (e) {
                console.error(`重命名失败: ${item}`, e);
            }
        }

        if (stat.isDirectory()) {
            renameEncodedItems(fullPath);
        }
    });
}

// Main processing function
async function processFiles() {
    console.log('开始处理静态网页...');
    
    // 0. Initial rename to ensure we work with correct filenames
    renameEncodedItems(OUTPUT_DIR);

    // Clean up unwanted .txt files (RSC payloads)
    function cleanUnwantedFiles(dir) {
        if (!fs.existsSync(dir)) return;
        const files = fs.readdirSync(dir);
        files.forEach(file => {
            const filePath = path.join(dir, file);
            const stat = fs.statSync(filePath);
            if (stat.isDirectory()) {
                cleanUnwantedFiles(filePath);
            } else {
                if (path.extname(file) === '.txt' && file !== 'README.txt') {
                    fs.unlinkSync(filePath);
                }
            }
        });
    }
    cleanUnwantedFiles(OUTPUT_DIR);
    
    // 1. Get all HTML files in output directory
    const htmlFiles = fs.readdirSync(OUTPUT_DIR).filter(f => f.endsWith('.html'));
    
    for (const file of htmlFiles) {
        if (file === '404.html') continue; // Skip 404
        
        const filePath = path.join(OUTPUT_DIR, file);
        const fileName = path.basename(file, '.html');
        console.log(`Processing: ${file}`);
        
        // 2. Read the exported HTML
        const content = fs.readFileSync(filePath, 'utf8');
        
        // 3. Parse with JSDOM to extract the main content
        const dom = new JSDOM(content);
        const doc = dom.window.document;
        
        // We need to find the main content container. 
        // Based on the source code, it's usually inside <div class="chd-renderer-root"> or similar.
        // Or we can just grab the entire body content, but we want to strip Next.js scripts.
        
        // In the static export, the content is rendered.
        // Let's try to find the CHDRenderer root or just take the body and strip scripts.
        
        // Remove Next.js scripts
        const scripts = doc.querySelectorAll('script');
        scripts.forEach(script => script.remove());
        
        // Remove Next.js hidden data
        const nextData = doc.getElementById('__NEXT_DATA__');
        if (nextData) nextData.remove();
        
        // Extract body content
        // We specifically want the rendered content.
        // If we look at the raw export, it has a lot of wrapper divs.
        // Ideally we want to find the container that corresponds to the 'editor preview'.
        // But for safety, let's take the body content and wrap it.
        let bodyContent = doc.body.innerHTML;
        
        // 4. Construct the new HTML
        const theme = 'ocean'; // Default theme, or try to detect from metadata?
        // Ideally we should match the theme used in the post, but that info is in the frontmatter.
        // For now, we use a safe default.
        
        const themeScript = `
            // Force sync theme
            document.documentElement.setAttribute('data-theme', '${theme}');
        `;
        
        const fullHtml = HTML_TEMPLATE
            .replace('{{TITLE}}', fileName)
            .replace('{{THEME}}', theme)
            .replace('{{CONTENT}}', bodyContent)
            .replace('{{CSS}}', GLOBAL_CSS) // Inject the extracted CSS
            .replace('{{THEME_SCRIPT}}', themeScript)
            .replace('{{SCRIPT}}', `
                document.addEventListener('DOMContentLoaded', () => {
                    console.log('Document loaded (Single File Mode)');
                });
            `);
            
        // 5. Overwrite the file
        fs.writeFileSync(filePath, fullHtml, 'utf8');
    }
    
    // 6. Cleanup and Organization
    console.log('正在整理文件...');
    const SYSTEM_DIR = path.join(OUTPUT_DIR, 'system');
    if (!fs.existsSync(SYSTEM_DIR)) {
        fs.mkdirSync(SYSTEM_DIR, { recursive: true });
    }

    const files = fs.readdirSync(OUTPUT_DIR);
    
    // System files to move
    const systemFiles = ['404.html', 'index.html', 'editor.html', 'preview.html', 'test.html'];
    
    // Directories to remove
    const dirsToRemove = ['_next', 'api'];

    files.forEach(file => {
        const filePath = path.join(OUTPUT_DIR, file);
        const stat = fs.statSync(filePath);

        // Move system files
        if (systemFiles.includes(file)) {
            const destPath = path.join(SYSTEM_DIR, file);
            if (fs.existsSync(destPath)) fs.unlinkSync(destPath);
            fs.renameSync(filePath, destPath);
            return;
        }

        // Remove .txt files
        if (file.endsWith('.txt')) {
            fs.unlinkSync(filePath);
            return;
        }

        // Remove directories
        if (stat.isDirectory()) {
            if (dirsToRemove.includes(file)) {
                fs.rmSync(filePath, { recursive: true, force: true });
            }
        }
    });

    console.log('静态网页处理完成。');
}

processFiles().catch(console.error);
